language: go
go:
- master

before_install:
- if ! go get code.google.com/p/go.tools/cmd/vet; then go get golang.org/x/tools/cmd/vet; fi
- go get -v github.com/golang/lint/golint
- if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
-if ! go get github.com/smartystreets/goconvey/convey; then go get -v -u github.com/smartystreets/goconvey/convey; fi

